Repository darwinia-network/darwinia-common, pull requests merged in 2020-09, with the labels that each got.

#258 Bump Common Library
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  client/cli/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/relay/Cargo.toml
Labels: A0-pleasereview

#259 Refactor Ethereum Relay Verification
  .github/workflows/ci.yml
  .maintain/ci/format.sh
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/backing/src/tests.rs
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_0.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_1.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_2.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_3.rs
  frame/bridge/ethereum/relay/src/tests.rs
  frame/bridge/ethereum/relay/tests-data/game-2/proposal-0.json
  frame/bridge/ethereum/relay/tests-data/game-2/proposal-1.json
  frame/bridge/ethereum/relay/tests-data/game-2/proposal-2.json
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/support/src/traits.rs
  primitives/ethereum-primitives/Cargo.toml
  primitives/ethereum-primitives/src/ethashproof.rs
  primitives/ethereum-primitives/src/header.rs
  primitives/relay/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#265 Ropsten Backing Tests
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/backing/src/test_with_linear_relay.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/ethereum/backing/src/tests.rs
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/ethereum/relay/src/tests.rs
  primitives/ethereum-primitives/src/header.rs
  primitives/ethereum-primitives/src/receipt.rs
Labels: A0-pleasereview, D1-runtime-migration

#270 Add Inflation test
  Cargo.lock
  bin/node-template/node/src/chain_spec.rs
  frame/staking/Cargo.toml
  frame/staking/src/inflation.rs
  frame/staking/src/inflation_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/substrate_tests.rs
Labels: A0-pleasereview

#274 Add Crab Issuing Module
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/bridge/crab/issuing/Cargo.toml
  frame/bridge/crab/issuing/src/lib.rs
  frame/bridge/crab/issuing/src/mock.rs
  frame/bridge/crab/issuing/src/tests.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/relayer-game/src/lib.rs
Labels: A0-pleasereview

#277 Use Free Balance for Staking Bond
  frame/staking/src/lib.rs
  frame/support/src/structs.rs
Labels: A0-pleasereview

#282 Revert `Perquintill` to `Perbill`
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/staking/src/inflation.rs
  frame/staking/src/inflation_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
Labels: D2-remove-migration

#281 Fix last confirmed blocks
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/src/lib.rs
  docs/CODEOWNERS
  frame/bridge/ethereum/backing/src/test_with_linear_relay.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/ethereum/relay/src/tests.rs
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  primitives/ethereum-primitives/src/lib.rs
  primitives/relay/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, D1-runtime-migration, E1-new-types

#292 Add Vesting
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/bridge/crab/backing/src/lib.rs
  frame/bridge/crab/issuing/src/lib.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/vesting/Cargo.toml
  frame/vesting/src/lib.rs
Labels: A0-pleasereview

#291 Update Promise Month for Reward KTON
  frame/staking/src/lib.rs
Labels: A0-pleasereview

#299 KTON Reward Tests
  frame/staking/src/inflation.rs
  frame/staking/src/inflation_tests.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview

#302 Implement Extend Lock
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview

#301 Add Democracy
  Cargo.lock
  Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/src/weights/darwinia_democracy.rs
  bin/node-template/runtime/src/weights/mod.rs
  frame/democracy/Cargo.toml
  frame/democracy/src/conviction.rs
  frame/democracy/src/default_weight.rs
  frame/democracy/src/lib.rs
  frame/democracy/src/tests.rs
  frame/democracy/src/tests/cancellation.rs
  frame/democracy/src/tests/decoders.rs
  frame/democracy/src/tests/delegation.rs
  frame/democracy/src/tests/external_proposing.rs
  frame/democracy/src/tests/fast_tracking.rs
  frame/democracy/src/tests/lock_voting.rs
  frame/democracy/src/tests/preimage.rs
  frame/democracy/src/tests/public_proposals.rs
  frame/democracy/src/tests/scheduling.rs
  frame/democracy/src/tests/voting.rs
  frame/democracy/src/types.rs
  frame/democracy/src/vote.rs
  frame/democracy/src/vote_threshold.rs
Labels: A0-pleasereview

#304 Correct Staking Payout
  .github/workflows/ci.yml
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview, D1-runtime-migration, E1-new-types

#307 Fixes
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
Labels: A0-pleasereview, E1-new-types

#308 Remove Migration
  frame/staking/src/lib.rs
Labels: A0-pleasereview, D2-remove-migration

#309 Refactor Dust Collector
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/polkadot-compatible-types.json
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
  frame/balances/src/lib.rs
  frame/balances/src/tests_local.rs
  frame/bridge/crab/issuing/src/mock.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/linear-relay/src/mock.rs
  frame/bridge/ethereum/offchain/src/mock.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/claims/src/lib.rs
  frame/democracy/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/mock.rs
  frame/support/src/traits.rs
  frame/treasury/src/mock.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview

#310 Release 1.0.0-beta.1
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  client/cli/Cargo.toml
  docs/CODEOWNERS
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/crab/backing/Cargo.toml
  frame/bridge/crab/issuing/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/tron/backing/Cargo.toml
  frame/claims/Cargo.toml
  frame/democracy/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/relay/Cargo.toml
Labels: A0-pleasereview

#312 Optimize Staking Pool Management
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/slashing.rs
Labels: A0-pleasereview

#313 Optional Staking Migration
  frame/staking/src/lib.rs
Labels: A0-pleasereview, D1-runtime-migration

#315 Release 1.0.0
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  client/cli/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/crab/backing/Cargo.toml
  frame/bridge/crab/issuing/Cargo.toml
  frame/bridge/crab/issuing/src/lib.rs
  frame/bridge/crab/issuing/src/mock.rs
  frame/bridge/crab/issuing/src/tests.rs
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/tron/backing/Cargo.toml
  frame/bridge/tron/backing/src/lib.rs
  frame/claims/Cargo.toml
  frame/democracy/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/staking/src/lib.rs
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/relay/Cargo.toml
Labels: D2-remove-migration

#317 NO-OP if Deposit Zero
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview
