Repository darwinia-network/darwinia-common, pull requests merged in 2020-07, with the labels that each got.

#172 Bump Deps Version
  Cargo.lock
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/claims/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/support/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
Labels: A0-pleasereview

#181 Hotfix Underflow
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/substrate_tests.rs
Labels: A0-pleasereview

#170 Relayer Game Tests
  Cargo.lock
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/relayer-game/README.md
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/bridge/relayer-game/src/tests.rs
  frame/support/src/structs.rs
  frame/support/src/traits.rs
Labels: B2-breaksapi

#179 Fix mmr size in gen proof, Fixed #177
  Cargo.lock
  bin/node-template/node/src/rpc.rs
  bin/node-template/runtime/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/runtime-api/src/lib.rs
  frame/header-mmr/rpc/src/lib.rs
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/tests.rs
Labels: A0-pleasereview

#184 Relayer Game Event
  bin/node-template/runtime/src/lib.rs
  frame/bridge/relayer-game/README.md
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi

#167 Ethereum Relay
  .travis.yml
  Cargo.lock
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/linear-relay/src/mock.rs
  frame/bridge/ethereum/linear-relay/src/tests.rs
  frame/bridge/ethereum/offchain/src/lib.rs
  frame/bridge/ethereum/offchain/src/tests.rs
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/build.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mmr.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/ethereum/relay/src/test-data/0.json
  frame/bridge/ethereum/relay/src/test-data/1.json
  frame/bridge/ethereum/relay/src/test-data/2.json
  frame/bridge/ethereum/relay/src/test-data/3.json
  frame/bridge/ethereum/relay/src/test-data/8996776.json
  frame/bridge/ethereum/relay/src/tests.rs
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/support/src/structs.rs
  primitives/ethereum-primitives/Cargo.toml
  primitives/ethereum-primitives/src/error.rs
  primitives/ethereum-primitives/src/header.rs
  primitives/ethereum-primitives/src/lib.rs
  primitives/ethereum-primitives/src/merkle.rs
  primitives/ethereum-primitives/src/pow.rs
Labels: A0-pleasereview

#190 Add check receipt api
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/linear-relay/src/mock.rs
  frame/bridge/ethereum/offchain/src/lib.rs
  frame/bridge/ethereum/offchain/src/mock.rs
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mmr.rs
  frame/bridge/ethereum/relay/src/mock.rs
  frame/bridge/relayer-game/src/lib.rs
  frame/bridge/relayer-game/src/mock.rs
  primitives/ethereum-primitives/Cargo.toml
  primitives/ethereum-primitives/src/error.rs
  primitives/ethereum-primitives/src/ethashproof.rs
  primitives/ethereum-primitives/src/header.rs
  primitives/ethereum-primitives/src/lib.rs
  primitives/ethereum-primitives/src/pow.rs
  primitives/ethereum-primitives/src/receipt.rs
Labels: A0-pleasereview

#194 Darwinia Relay
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/src/lib.rs
Labels: A0-pleasereview

#196 Using the codec of HeaderThing structs in the test data of ETH Relay
  frame/bridge/ethereum/relay/src/mock/mod.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_0.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_1.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_2.rs
  frame/bridge/ethereum/relay/src/mock/test_data/header_thing_3.rs
  frame/bridge/ethereum/relay/src/test-data/0.json
  frame/bridge/ethereum/relay/src/test-data/1.json
  frame/bridge/ethereum/relay/src/test-data/2.json
  frame/bridge/ethereum/relay/src/test-data/3.json
  frame/bridge/ethereum/relay/src/test-data/8996776.json
  frame/bridge/ethereum/relay/src/tests.rs
Labels: A0-pleasereview

#195 Substrate RC3
  .travis.yml
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/build.rs
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  client/cli/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/relayer-game/Cargo.toml
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
Labels: A0-pleasereview

#199 Patches
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/backing/src/tests.rs
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/linear-relay/src/mock.rs
  frame/bridge/ethereum/linear-relay/src/tests.rs
  frame/bridge/ethereum/offchain/src/lib.rs
  frame/bridge/ethereum/offchain/src/mock.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/ethereum/relay/src/mock/mod.rs
  frame/bridge/ethereum/relay/src/tests.rs
  frame/staking/src/lib.rs
Labels: A0-pleasereview

#202 Fix Repo Link
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  client/cli/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
Labels: A0-pleasereview
