Repository darwinia-network/darwinia-common, pull requests merged in 2020-04, with the labels that each got.

#29 Code Clean
  .editorconfig
  .maintain/types/types.json
  .maintain/utility/clean-offchain-builds.py
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/build.rs
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/build.rs
  bin/node-template/runtime/src/impls.rs
  bin/node-template/runtime/src/lib.rs
  frame/balances/Cargo.toml
  frame/balances/src/benchmarking.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/chainrelay/eth/backing/Cargo.toml
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/backing/src/tests.rs
  frame/chainrelay/eth/offchain/Cargo.toml
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/offchain/src/tests.rs
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/lib.rs
  frame/chainrelay/eth/relay/src/mock.rs
  frame/chainrelay/eth/relay/src/mock_headers/mod.rs
  frame/chainrelay/eth/relay/src/mock_headers/utils.rs
  frame/chainrelay/eth/relay/src/tests.rs
  frame/claims/Cargo.toml
  frame/claims/src/address.rs
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/mock.rs
  frame/header-mmr/src/tests.rs
  frame/staking/Cargo.toml
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/support/src/lib.rs
  frame/support/src/macros.rs
  frame/support/src/structs.rs
  frame/support/src/traits.rs
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/mock.rs
  frame/treasury/src/tests.rs
  frame/vesting/Cargo.toml
  frame/vesting/src/lib.rs
Labels: A0-pleasereview

#36 Refactor header mmr to use Other Digest Item Type
  .maintain/types/types.json
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  frame/balances/Cargo.toml
  frame/chainrelay/eth/backing/Cargo.toml
  frame/chainrelay/eth/offchain/Cargo.toml
  frame/chainrelay/eth/relay/Cargo.toml
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/mock.rs
  frame/header-mmr/src/tests.rs
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
Labels: A0-pleasereview

#38 Refactor eth network const and subkey prefix
  bin/node-template/runtime/src/lib.rs
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/relay/src/lib.rs
  frame/chainrelay/eth/relay/src/mock.rs
  frame/staking/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview

#39 Add redeem address set call
  frame/chainrelay/eth/backing/src/lib.rs
Labels: A0-pleasereview

#41 update: new `DustCollector`
  Cargo.lock
  bin/node-template/runtime/src/lib.rs
  frame/balances/src/lib.rs
  frame/balances/src/tests_local.rs
  frame/chainrelay/eth/backing/src/mock.rs
  frame/claims/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/support/Cargo.toml
  frame/support/src/lib.rs
  frame/support/src/traits.rs
  frame/treasury/src/mock.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview

#42 Fix Bug
  Cargo.lock
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
  frame/balances/src/lib.rs
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/relay/src/lib.rs
Labels: A0-pleasereview

#46 Upgrade Substrate
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
  frame/balances/Cargo.toml
  frame/balances/src/lib.rs
  frame/balances/src/tests_local.rs
  frame/chainrelay/eth/backing/Cargo.toml
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/offchain/Cargo.toml
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/mock.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/mock.rs
  frame/staking/Cargo.toml
  frame/staking/src/benchmarking.rs
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/mock.rs
  frame/treasury/src/tests.rs
  frame/vesting/Cargo.toml
  frame/vesting/src/lib.rs
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
  primitives/phragmen/src/lib.rs
  primitives/phragmen/src/mock.rs
  primitives/phragmen/src/tests.rs
Labels: A0-pleasereview

#48 Using unique name for module storage
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/relay/src/lib.rs
  frame/claims/src/lib.rs
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/src/lib.rs
  frame/staking/src/lib.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview

#43 Get token from offchain db
  bin/node-template/runtime/src/lib.rs
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/offchain/src/mock.rs
Labels: A0-pleasereview

#49 Upgrade Substrate
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
  frame/balances/Cargo.toml
  frame/chainrelay/eth/backing/Cargo.toml
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/offchain/Cargo.toml
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/offchain/src/tests.rs
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/lib.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/tests.rs
  frame/staking/Cargo.toml
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/support/src/traits.rs
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
Labels: A3-inprogress, B2-breaksapi

#61 update gitignore
  .gitignore
Labels: A0-pleasereview

#54 Refactor backing Module
  bin/node-template/runtime/src/lib.rs
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/backing/src/tests.rs
  frame/elections-phragmen/src/lib.rs
  frame/staking/src/lib.rs
  frame/support/src/traits.rs
  frame/treasury/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#65 Upgrade rust-ethash and fix ethash
  Cargo.lock
  Cargo.toml
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/lib.rs
  primitives/eth-primitives/Cargo.toml
  primitives/eth-primitives/src/header.rs
  primitives/ethash/Cargo.toml
  primitives/ethash/src/dag.rs
  primitives/ethash/src/lib.rs
  primitives/ethash/src/miller_rabin.rs
Labels: A0-pleasereview

#60 Support `EthHeader::from_str_unchecked`
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/impls.rs
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/offchain/src/tests.rs
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/lib.rs
  frame/chainrelay/eth/relay/src/mock.rs
  frame/chainrelay/eth/relay/src/mock_headers/check_receipt.rs
  frame/chainrelay/eth/relay/src/mock_headers/mod.rs
  frame/chainrelay/eth/relay/src/mock_headers/utils.rs
  frame/chainrelay/eth/relay/src/tests.rs
  frame/claims/src/address.rs
  frame/claims/src/lib.rs
  frame/support/src/lib.rs
  frame/support/src/macros.rs
  primitives/eth-primitives/Cargo.toml
  primitives/eth-primitives/src/header.rs
  primitives/eth-primitives/src/receipt.rs
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
Labels: A0-pleasereview

#66 Disable hashimoto in tests and rename chainrelay folder to bridge
  Cargo.toml
  bin/node-template/runtime/Cargo.toml
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/README.md
  frame/bridge/eth/backing/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/README.md
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/tests.rs
Labels: A0-pleasereview

#68 Update Types
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/runtime/src/lib.rs
  bin/node-template/runtime/types.json
Labels: A0-pleasereview

#63 Multiple Ethereum resource
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
Labels: A0-pleasereview

#77 Ethashproof Patch
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/res/dag_merkle_roots.json
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/data/dag_merkle_roots.json
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/mock_mainnet.rs
  frame/bridge/eth/relay/src/test-data/8996776.json
  frame/bridge/eth/relay/src/test-data/8996777.json
  frame/bridge/eth/relay/src/test-data/8996778.json
  frame/bridge/eth/relay/src/tests.rs
  frame/bridge/eth/relay/src/tests_mainnet.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/staking/src/mock.rs
  frame/support/src/macros.rs
Labels: A0-pleasereview

#70 Optimize darwinia-eth-relay using ethashproof
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/res/dag_merkle_roots.json
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/test-data/8996776.json
  frame/bridge/eth/relay/src/test-data/8996777.json
  frame/bridge/eth/relay/src/test-data/8996778.json
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/staking/src/mock.rs
  frame/support/src/macros.rs
Labels: A0-pleasereview

#78 Add Feature `build-spec`
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
  frame/support/Cargo.toml
Labels: A0-pleasereview

#80 request from a dummy domain
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
Labels: A0-pleasereview

#82 Storage Migration for eth-relay
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/relay/src/lib.rs
  frame/claims/src/lib.rs
  primitives/eth-primitives/Cargo.toml
  primitives/eth-primitives/src/header.rs
  primitives/eth-primitives/src/pow.rs
  primitives/eth-primitives/src/receipt.rs
Labels: A0-pleasereview

#84 Add Balances RPC
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/node/res/dag_merkle_roots.json
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/main.rs
  bin/node-template/node/src/rpc.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/balances/rpc/runtime-api/src/lib.rs
  frame/balances/rpc/src/lib.rs
  frame/balances/src/lib.rs
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
Labels: A0-pleasereview

#87 Update Types
  Cargo.lock
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/lib.rs
  frame/claims/Cargo.toml
  frame/claims/src/address.rs
  frame/claims/src/lib.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview

#89 Modify offchain protocol with scale
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/tests.rs
  primitives/eth-primitives/src/header.rs
Labels: A0-pleasereview

#93 refactor offchain worker
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/src/address.rs
  frame/claims/src/lib.rs
  frame/support/src/lib.rs
  frame/support/src/macros.rs
  primitives/eth-primitives/src/header.rs
  primitives/eth-primitives/src/receipt.rs
Labels: A0-pleasereview

#90 Using signed extension for relay_header
  .travis.yml
  Cargo.lock
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/src/address.rs
Labels: A0-pleasereview

#88 Support Offchain Phragmen
  Cargo.lock
  Cargo.toml
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/balances/src/tests_local.rs
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/support/src/structs.rs
  frame/treasury/Cargo.toml
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/phragmen/Cargo.toml
  primitives/phragmen/src/lib.rs
  primitives/phragmen/src/mock.rs
  primitives/phragmen/src/tests.rs
Labels: A0-pleasereview

#95 Add offchain test
  Cargo.lock
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/header-mmr/Cargo.toml
Labels: A0-pleasereview

#102 Upgrade to Substrate Alpha.6
  .editorconfig
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/build.rs
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/cli.rs
  bin/node-template/node/src/command.rs
  bin/node-template/node/src/main.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/balances/src/benchmarking.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/tests.rs
  frame/staking/Cargo.toml
  frame/staking/README.md
  frame/staking/src/benchmarking.rs
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/mock.rs
  frame/treasury/src/tests.rs
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
Labels: A0-pleasereview

#105 More strict check for EthHeader PartialEq
  primitives/eth-primitives/src/header.rs
Labels: A0-pleasereview

#111 Upgrade Substrate to 31d5d3
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/node/src/chain_spec.rs
  bin/node-template/node/src/service.rs
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  docs/CODEOWNERS
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/balances/src/lib.rs
  frame/balances/src/tests.rs
  frame/balances/src/tests_local.rs
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/Cargo.toml
  frame/claims/src/lib.rs
  frame/elections-phragmen/Cargo.toml
  frame/elections-phragmen/src/lib.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/mock.rs
  frame/staking/Cargo.toml
  frame/staking/src/inflation.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  frame/support/Cargo.toml
  frame/support/src/macros.rs
  frame/support/src/structs.rs
  frame/treasury/Cargo.toml
  frame/treasury/src/lib.rs
  frame/treasury/src/mock.rs
  frame/treasury/src/tests.rs
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
Labels: A0-pleasereview

#108 Relayer incentive model
  Cargo.lock
  bin/node-template/runtime/darwinia_types.json
  bin/node-template/runtime/polkadot_compatible_types.json
  bin/node-template/runtime/src/lib.rs
  frame/bridge/eth/backing/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/tests.rs
Labels: A0-pleasereview

#114 easy-testing for eth-primitives
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/relay/Cargo.toml
  primitives/eth-primitives/Cargo.toml
  primitives/eth-primitives/src/header.rs
Labels: A0-pleasereview

#107 Update bootstrap.sh
  .maintain/bootstrap.sh
Labels: A0-pleasereview

#116 Sync Version With Kusama
  Cargo.lock
  bin/node-template/node/Cargo.toml
  bin/node-template/runtime/Cargo.toml
  bin/node-template/runtime/src/lib.rs
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/eth/backing/Cargo.toml
  frame/bridge/eth/backing/src/lib.rs
  frame/bridge/eth/backing/src/mock.rs
  frame/bridge/eth/backing/src/tests.rs
  frame/bridge/eth/offchain/Cargo.toml
  frame/bridge/eth/offchain/src/mock.rs
  frame/bridge/eth/relay/Cargo.toml
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/tests.rs
  frame/claims/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/offchain_election.rs
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  primitives/eth-primitives/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
Labels: A0-pleasereview

#104 rm legacy compatiable api on eth-relay
  frame/bridge/eth/offchain/src/lib.rs
  frame/bridge/eth/offchain/src/tests.rs
  frame/bridge/eth/relay/src/lib.rs
  frame/bridge/eth/relay/src/mock.rs
  frame/bridge/eth/relay/src/test-data/ropsten_child_7575769_scale.json
  frame/bridge/eth/relay/src/test-data/ropsten_current_7575768_scale.json
  frame/bridge/eth/relay/src/test-data/ropsten_grandpa_7575766_scale.json
  frame/bridge/eth/relay/src/test-data/ropsten_origin_7575765_scale.json
  frame/bridge/eth/relay/src/test-data/ropsten_parent_7575767_scale.json
  frame/bridge/eth/relay/src/test-data/ropsten_uncle_7575766_scale.json
  frame/bridge/eth/relay/src/tests.rs
  frame/support/src/lib.rs
Labels: A0-pleasereview

#120 Modify default url for shadow service
  frame/bridge/eth/offchain/src/lib.rs
Labels: A0-pleasereview
