Repository darwinia-network/darwinia-common, pull requests merged in 2020-12, with the labels that each got.

#384 Add dvm web3 test
  .github/workflows/ci.yml
  .gitignore
  frame/dvm/script_tests/package-lock.json
  frame/dvm/script_tests/package.json
  frame/dvm/script_tests/tests/contract/Incrementer.sol
  frame/dvm/script_tests/tests/contract/compile.js
  frame/dvm/script_tests/tests/contract/test-constract-method.js
  frame/dvm/script_tests/tests/test-rpc-block.js
  frame/dvm/script_tests/tests/test-rpc-constants.js
  frame/dvm/script_tests/tests/test-transfer-balance.js
Labels: A0-pleasereview

#392 Code Clean
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  client/cli/Cargo.toml
  client/dvm/consensus/Cargo.toml
  client/dvm/rpc/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/crab/backing/Cargo.toml
  frame/bridge/crab/issuing/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/tron/backing/Cargo.toml
  frame/claims/Cargo.toml
  frame/democracy/Cargo.toml
  frame/dvm/Cargo.toml
  frame/dvm/rpc/Cargo.toml
  frame/dvm/rpc/runtime-api/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/evm/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/treasury/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/dvm-rpc-core/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/evm/Cargo.toml
Labels: A0-pleasereview

#391 Change name of mmr root to parent mmr root, related #380
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/mock.rs
  frame/header-mmr/src/tests.rs
Labels: A0-pleasereview

#389 Relay Authorities Test
  bin/node/cli/src/command.rs
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
Labels: A0-pleasereview

#394 Update evm crate version
  Cargo.lock
  bin/node/runtime/pangolin/src/lib.rs
  client/dvm/rpc/src/eth.rs
  frame/dvm/Cargo.toml
  frame/dvm/rpc/runtime-api/src/lib.rs
  frame/dvm/src/lib.rs
  frame/dvm/src/tests.rs
  frame/evm/Cargo.toml
  frame/evm/src/lib.rs
  frame/evm/src/runner/builtin.rs
  frame/evm/src/runner/mod.rs
  frame/evm/src/runner/stack.rs
  frame/header-mmr/src/lib.rs
  primitives/evm/Cargo.toml
Labels: A0-pleasereview

#395 Pangolin Updates
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/primitives/Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
  frame/evm/src/lib.rs
Labels: A0-pleasereview

#397 Deposit Sign-Target Block Number while Locking
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview

#398 Bump Version
  Cargo.lock
  client/cli/Cargo.toml
  client/dvm/consensus/Cargo.toml
  client/dvm/rpc/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/bridge/crab/backing/Cargo.toml
  frame/bridge/crab/issuing/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/offchain/Cargo.toml
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/bridge/tron/backing/Cargo.toml
  frame/claims/Cargo.toml
  frame/democracy/Cargo.toml
  frame/dvm/Cargo.toml
  frame/dvm/rpc/Cargo.toml
  frame/dvm/rpc/runtime-api/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/evm/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/support/Cargo.toml
  frame/treasury/Cargo.toml
  frame/vesting/Cargo.toml
  primitives/array-bytes/Cargo.toml
  primitives/consensus/Cargo.toml
  primitives/dvm-rpc-core/Cargo.toml
  primitives/ethereum-primitives/Cargo.toml
  primitives/evm/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/relay/Cargo.toml
  script_tests/tests/test-web3api.js
Labels: A0-pleasereview, D2-remove-migration

#399 Add Claim Mature Deposits Event
  frame/staking/src/lib.rs
Labels: A0-pleasereview

#401 Add Relay Authorities Genesis
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview, D1-runtime-migration

#402 Use Eth Recover
  Cargo.lock
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
Labels: A0-pleasereview

#404 Merge from Pangolin
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/primitives/Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
Labels: A0-pleasereview, D2-remove-migration

#405 Update Types
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/types.json
Labels: A0-pleasereview, E1-new-types

#406 Expose Advanced Fee for Front-End Usage
  frame/bridge/ethereum/backing/src/lib.rs
Labels: A0-pleasereview

#407 Hash Message
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
  primitives/relay/src/relay_authorities.rs
Labels: A0-pleasereview, D1-runtime-migration, E1-new-types

#410 Update Events
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview

#412 deposit: asset address & use h160 for ecdsa address
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
Labels: A0-pleasereview, E1-new-types

#414 fix: always return some
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/tests.rs
Labels: A0-pleasereview

#415 update: format
  Cargo.lock
  LICENSE
  bin/node/cli/Cargo.toml
  bin/node/primitives/Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
  client/dvm/rpc/src/eth.rs
  client/dvm/rpc/src/lib.rs
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/democracy/src/tests/decoders.rs
  frame/dvm/rpc/runtime-api/src/lib.rs
  frame/dvm/rpc/src/eth.rs
  frame/dvm/rpc/src/eth_pubsub.rs
  frame/dvm/rpc/src/net.rs
  frame/dvm/rpc/src/web3.rs
  frame/dvm/src/lib.rs
  frame/dvm/src/mock.rs
  frame/header-mmr/rpc/runtime-api/src/lib.rs
  frame/header-mmr/src/lib.rs
  primitives/dvm-rpc-core/src/account_info.rs
  primitives/dvm-rpc-core/src/block.rs
  primitives/dvm-rpc-core/src/block_number.rs
  primitives/dvm-rpc-core/src/bytes.rs
  primitives/dvm-rpc-core/src/call_request.rs
  primitives/dvm-rpc-core/src/filter.rs
  primitives/dvm-rpc-core/src/index.rs
  primitives/dvm-rpc-core/src/lib.rs
  primitives/dvm-rpc-core/src/log.rs
  primitives/dvm-rpc-core/src/pubsub.rs
  primitives/dvm-rpc-core/src/receipt.rs
  primitives/dvm-rpc-core/src/sync.rs
  primitives/dvm-rpc-core/src/transaction.rs
  primitives/dvm-rpc-core/src/transaction_request.rs
  primitives/dvm-rpc-core/src/work.rs
  primitives/relay/src/lib.rs
  primitives/relay/src/relay_authorities.rs
  primitives/relay/src/relayer_game.rs
Labels: A0-pleasereview

#416 Sync Authorities Set
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/backing/src/test_with_linear_relay.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/relay-authorities/src/lib.rs
  primitives/relay/src/relay_authorities.rs
Labels: A0-pleasereview, D1-runtime-migration, E1-new-types

#418 fix(relay authorities): should increase `AuthorityTerm`
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview

#423 feat(relay authorities): public constants
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview

#424 Merge from Pangolin
  Cargo.lock
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/types.json
Labels: A0-pleasereview, E1-new-types

#425 feat(relay authorities): reset authorities
  frame/bridge/relay-authorities/src/lib.rs
Labels: A0-pleasereview
