Repository darwinia-network/darwinia-common, pull requests merged in 2021-06, with the labels that each got.

#649 Upgrade Ethereum pallet to FRAMEv2
  bin/node/runtime/pangolin/src/lib.rs
  frame/bridge/ethereum/issuing/src/lib.rs
  frame/dvm/rpc/runtime-api/src/lib.rs
  frame/dvm/rpc/src/eth.rs
  frame/dvm/rpc/src/eth_pubsub.rs
  frame/dvm/rpc/src/lib.rs
  frame/dvm/rpc/src/net.rs
  frame/dvm/rpc/src/web3.rs
  frame/dvm/src/account_basic.rs
  frame/dvm/src/lib.rs
  frame/dvm/src/mock.rs
  frame/dvm/src/tests.rs
Labels: P1 Low

#652 Abandon DarwiniaPrecompiles tuple
  Cargo.lock
  Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/pallets/evm.rs
  bin/node/runtime/pangolin/src/pallets/evm_.rs
  bin/node/runtime/pangolin/src/pallets/mod.rs
  frame/bridge/ethereum/issuing/Cargo.toml
  frame/evm/precompile/Cargo.toml
  frame/evm/precompile/contracts/kton/src/lib.rs
  frame/evm/precompile/src/lib.rs
Labels: DVM

#648 Upgrade EVM pallet to FRAMEv2
  bin/node/runtime/pangolin/src/lib.rs
  frame/dvm-dynamic-fee/src/lib.rs
  frame/evm/precompile/contracts/kton/src/lib.rs
  frame/evm/src/lib.rs
  frame/evm/src/runner/mod.rs
  frame/evm/src/runner/stack.rs
  frame/evm/src/tests.rs
Labels: Break Storage

#661 Close #630
  frame/bridge/ethereum/linear-relay/src/lib.rs
  frame/evm/src/lib.rs
  frame/evm/src/runner/stack.rs
Labels: Slient

#662 Update `array-bytes`
  Cargo.lock
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/pangolin/Cargo.toml
  client/dvm/rpc/Cargo.toml
  frame/bridge/ethereum/backing/Cargo.toml
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/test_with_linear_relay.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/ethereum/linear-relay/Cargo.toml
  frame/bridge/ethereum/linear-relay/src/mock.rs
  frame/bridge/ethereum/relay/Cargo.toml
  frame/bridge/ethereum/relay/src/lib.rs
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relay-authorities/src/test.rs
  frame/claims/Cargo.toml
  frame/claims/src/address.rs
  frame/claims/src/lib.rs
  frame/dvm/Cargo.toml
  frame/evm/precompile/contracts/kton/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/src/tests.rs
  primitives/ethereum-primitives/Cargo.toml
  primitives/ethereum-primitives/src/ethashproof.rs
  primitives/ethereum-primitives/src/header.rs
  primitives/ethereum-primitives/src/receipt.rs
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/merkle-patricia-trie/src/lib.rs
Labels: Dependency Update, Slient

#646 Add `ethereum-bsc`
  Cargo.lock
  Cargo.toml
  bin/node/cli/Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/src/pallets/bridge_bsc.rs
  bin/node/runtime/pangolin/src/pallets/mod.rs
  frame/bridge/ethereum-bsc/Cargo.toml
  frame/bridge/ethereum-bsc/src/lib.rs
  frame/bridge/ethereum-bsc/src/mock.rs
  frame/bridge/ethereum-bsc/src/tests.rs
  primitives/chain-bsc/Cargo.toml
  primitives/chain-bsc/src/lib.rs
Labels: Bridge

#673 MMR Support Pruning
  Cargo.lock
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/src/pallets/header_mmr.rs
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
  frame/header-mmr/Cargo.toml
  frame/header-mmr/mmr.json
  frame/header-mmr/rpc/runtime-api/src/lib.rs
  frame/header-mmr/rpc/src/lib.rs
  frame/header-mmr/src/lib.rs
  frame/header-mmr/src/mock.rs
  frame/header-mmr/src/primitives.rs
  frame/header-mmr/src/tests.rs
  frame/header-mmr/src/weights.rs
  primitives/relay/src/relay_authorities.rs
Labels: Break API, Break Storage, Break Type Definition, Crab, Darwinia, Migration Added, P9 High

#679 Set Cross Compile Minimal Support to Ubuntu 16.04
  .maintain/docker/Dockerfile
  .maintain/docker/Dockerfile.aarch64-linux-gnu
  .maintain/docker/Dockerfile.arm-linux-gnueabihf
  .maintain/docker/Dockerfile.armv7-linux-gnueabihf
  .maintain/docker/Dockerfile.x86_64-linux-gnu
Labels: Pangolin, Slient

#681 Benchmark WASM
  bin/node/runtime/pangolin/src/lib.rs
Labels: Pangolin, Slient

#683 Update Metadata Types
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
Labels: Break Type Definition, Pangolin
