Repository darwinia-network/darwinia-common, pull requests merged in 2021-09, with the labels that each got.

#801 `npm audit fix`
  tests/dvm/package-lock.json
Labels: Test Improvement

#800 Lock Dependencies
  .github/workflows/ci.yml
Labels: CI/CD

#790 Added a brief intro to each module
  README.md
Labels: Documentation

#802 Usage document
  .gitignore
  README.md
  tests/local-testnet/deploy.sh
Labels: Documentation

#803 Companion for #frontier-465
  frame/dvm/src/lib.rs
Labels: DVM, Crab, Pangolin

#804 Update Address Type
  node/runtime/pangoro/types.json
Labels: Break Type Definition, Pangoro

#808 Update parity-bridges-common
  Cargo.lock
  frame/wormhole/backing/tron/src/lib.rs
  node/primitives/bridge/src/lib.rs
  node/runtime/pangolin/src/bridges/substrate/pangoro_messages.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangoro/src/impls.rs
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/transaction_payment.rs
  node/runtime/pangoro/src/pangolin_messages.rs
Labels: Migration Added, Bridge, Pangolin, Pangoro

#815 Add Scheduler for Pangoro
  Cargo.lock
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pallets/scheduler.rs
Labels: Pangoro

#818 `pallet-balances` Document
  frame/balances/src/lib.rs
Labels: Documentation

#827 Correct Document
  frame/wormhole/backing/s2s/src/lib.rs
Labels: Documentation

#817 Update dvm from 426 to 435
  Cargo.lock
  client/dvm/db/Cargo.toml
  client/dvm/db/src/lib.rs
  client/dvm/mapping-sync/src/lib.rs
  client/dvm/mapping-sync/src/worker.rs
  client/dvm/rpc/src/eth.rs
  client/dvm/rpc/src/lib.rs
  frame/dvm-dynamic-fee/Cargo.toml
  frame/dvm-dynamic-fee/src/lib.rs
  frame/dvm/src/lib.rs
  node/rpc/src/pangolin.rs
  node/runtime/pangoro/src/pallets/transaction_payment.rs
  node/service/src/service/pangolin.rs
  primitives/storage/src/lib.rs
  tests/dvm/tests/0_test-rpc-block.js
Labels: P8 High

#830 Update Types
  node/runtime/pangolin/polkadot-compatible-types.json
  node/runtime/pangolin/types.json
  node/runtime/pangoro/types.json
Labels: Break Type Definition, Crab, Darwinia, Pangolin, Pangoro

#832 Move `PANGORO_PANGOLIN_LANE` to `bridge-primitives` and Renew `LaneId`
  node/primitives/bridge/src/lib.rs
  node/runtime/pangolin/src/bridges/substrate/pangoro_messages.rs
  node/runtime/pangolin/src/pallets/bridge_messages.rs
  node/runtime/pangolin/src/pallets/from_substrate_issuing_.rs
  node/runtime/pangoro/src/pallets/bridge_message.rs
  node/runtime/pangoro/src/pallets/to_substrate_backing_.rs
  node/runtime/pangoro/src/pangolin_messages.rs
Labels: Pangolin, Pangoro

#833 Update Types
  node/runtime/pangolin/types.json
Labels: Break Type Definition

#834 Add Rustdoc to CI
  .github/workflows/release.yml
  vercel.json
Labels: Documentation, CI/CD

#838 BridgeMessageId=>TokenMessageId
  frame/evm/precompile/contracts/encoder/src/lib.rs
  frame/support/src/lib.rs
  frame/wormhole/backing/s2s/src/lib.rs
  frame/wormhole/backing/s2s/src/tests.rs
  frame/wormhole/issuing/s2s/src/lib.rs
  frame/wormhole/issuing/s2s/src/tests.rs
  node/runtime/pangolin/polkadot-compatible-types.json
  node/runtime/pangolin/src/pallets/from_substrate_issuing_.rs
  node/runtime/pangolin/types.json
  node/runtime/pangoro/src/pallets/to_substrate_backing_.rs
Labels: Break Type Definition

#836 Polish Rustdoc CI
  .github/workflows/release.yml
  vercel.json
Labels: CI/CD

#840 Fix Polkadot JS Balance Lock Relateds
  node/runtime/pangolin/polkadot-compatible-types.json
Labels: Break Type Definition

#842 Improve CI
  .github/workflows/ci.yml
Labels: CI/CD
