Repository darwinia-network/darwinia-common, pull requests merged in 2021-11, with the labels that each got.

#906 Add Pallet `transaction-pause`
  .gitignore
  Cargo.lock
  Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/transaction-pause/src/lib.rs
  frame/transaction-pause/src/mock.rs
  frame/transaction-pause/src/tests.rs
  frame/transaction-pause/src/weights.rs
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/mod.rs
  node/runtime/pangolin/src/pallets/system/mod.rs
  node/runtime/pangolin/src/pallets/transaction_pause.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pallets/system/mod.rs
  node/runtime/pangoro/src/pallets/transaction_pause.rs
Labels: Pangolin, Pangoro

#922 Add RPC to query orders in progress
  Cargo.lock
  frame/fee-market/rpc/runtime-api/Cargo.toml
  frame/fee-market/rpc/runtime-api/src/lib.rs
  frame/fee-market/rpc/src/lib.rs
  frame/fee-market/src/lib.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/types.json
  node/runtime/pangoro/src/lib.rs
Labels: Break Type Definition, P7 High

#919 Optimization for precompile contract
  Cargo.lock
  Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/src/lib.rs
  frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
  frame/evm/precompile/contracts/bridge/s2s/src/lib.rs
  frame/evm/precompile/contracts/misc/src/lib.rs
  frame/evm/precompile/contracts/utils/Cargo.toml
  frame/evm/precompile/contracts/utils/macro/Cargo.toml
  frame/evm/precompile/contracts/utils/macro/src/lib.rs
  frame/evm/precompile/contracts/utils/src/lib.rs
  frame/wormhole/backing/s2s/src/lib.rs
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/pallets/evm_.rs
  primitives/contract/src/mapping_token_factory/s2s.rs
  primitives/evm/Cargo.toml
Labels: P8 High, Pangolin, Need Audit

#910 Locked collateral for each order
  Cargo.lock
  frame/fee-market/src/benchmarking.rs
  frame/fee-market/src/lib.rs
  frame/fee-market/src/s2s/callbacks.rs
  frame/fee-market/src/s2s/payment.rs
  frame/fee-market/src/tests.rs
  frame/fee-market/src/weight.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/fee_market.rs
  node/runtime/pangolin/types.json
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/fee_market.rs
  primitives/fee-market/src/lib.rs
Labels: Migration Added, Break Type Definition, Break Storage, P9 High, Pangolin, Pangoro

#924 Migration `darwinia-staking` to Attribute Macro
  Cargo.lock
  frame/staking/Cargo.toml
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/inflation.rs
  frame/staking/src/inflation_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/slashing.rs
  frame/staking/src/substrate_tests.rs
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
Labels: Break Storage

#944 Disable CI for Draft Pull Request
  .github/workflows/ci.yml
Labels: CI/CD

#947 Optimize CI
  .github/workflows/ci.yml
Labels: CI/CD

#949 Code Cleaning
  frame/wormhole/backing/tron/src/lib.rs
  frame/wormhole/issuing/s2s/src/tests.rs
  node/primitives/bridge/src/lib.rs
  node/runtime/pangolin/src/bridges/substrate/pangoro_messages.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/bridge_dispatch.rs
  node/runtime/pangolin/src/pallets/bridge_grandpa.rs
  node/runtime/pangolin/src/pallets/bridge_messages.rs
  node/runtime/pangolin/src/pallets/evm_.rs
  node/runtime/pangolin/src/pallets/fee_market.rs
  node/runtime/pangolin/types.json
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/bridge_dispatch.rs
  node/runtime/pangoro/src/pallets/bridge_grandpa.rs
  node/runtime/pangoro/src/pallets/bridge_messages.rs
  node/runtime/pangoro/src/pallets/fee_market.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pangolin_messages.rs
  primitives/s2s/src/call_params.rs
Labels: Housekeeping

#959 Reset Pangolin/Pangoro
  Cargo.lock
  Cargo.toml
  node/primitives/common/src/lib.rs
  node/runtime/common/Cargo.toml
  node/runtime/common/src/impls.rs
  node/runtime/common/src/lib.rs
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/constants/Cargo.toml
  node/runtime/pangolin/src/constants/src/lib.rs
  node/runtime/pangolin/src/impls.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/babe.rs
  node/runtime/pangolin/src/pallets/bounties.rs
  node/runtime/pangolin/src/pallets/bridge_grandpa.rs
  node/runtime/pangolin/src/pallets/collective.rs
  node/runtime/pangolin/src/pallets/democracy.rs
  node/runtime/pangolin/src/pallets/election_provider_multi_phase.rs
  node/runtime/pangolin/src/pallets/elections_phragmen.rs
  node/runtime/pangolin/src/pallets/fee_market.rs
  node/runtime/pangolin/src/pallets/multisig.rs
  node/runtime/pangolin/src/pallets/proxy.rs
  node/runtime/pangolin/src/pallets/relayer_game.rs
  node/runtime/pangolin/src/pallets/scheduler.rs
  node/runtime/pangolin/src/pallets/society.rs
  node/runtime/pangolin/src/pallets/staking.rs
  node/runtime/pangolin/src/pallets/system.rs
  node/runtime/pangolin/src/pallets/system/params/Cargo.toml
  node/runtime/pangolin/src/pallets/system/params/src/lib.rs
  node/runtime/pangolin/src/pallets/tips.rs
  node/runtime/pangolin/src/pallets/transaction_payment.rs
  node/runtime/pangolin/src/pallets/treasury.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/constants/Cargo.toml
  node/runtime/pangoro/src/constants/src/lib.rs
  node/runtime/pangoro/src/impls.rs
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/babe.rs
  node/runtime/pangoro/src/pallets/election_provider_multi_phase.rs
  node/runtime/pangoro/src/pallets/fee_market.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pallets/staking.rs
  node/runtime/pangoro/src/pallets/system.rs
  node/runtime/pangoro/src/pallets/system/params/Cargo.toml
  node/runtime/pangoro/src/pallets/system/params/src/lib.rs
  node/runtime/pangoro/src/pallets/transaction_pause.rs
  node/runtime/pangoro/src/pallets/transaction_payment.rs
  node/runtime/pangoro/src/pallets/treasury.rs
  node/service/src/chain_spec/pangolin.rs
  node/service/src/chain_spec/pangoro.rs
  primitives/contract/Cargo.toml
Labels: Pangolin, Pangoro

#960 Rebuild Genesis
  node/service/res/pangolin/pangolin.json
  node/service/res/pangoro/pangoro.json
Labels: Pangolin, Pangoro

#956 Improve CI
  .github/workflows/ci.yml
  .maintain/purge-large-cache.sh
Labels: CI/CD
