Repository darwinia-network/darwinia-common, pull requests merged in 2021-12, with the labels that each got.

#969 Drop Template Runtime on Unit Tests
  .github/workflows/ci.yml
Labels: CI/CD

#958 Improve DVM Tests
  .github/workflows/ci.yml
  .gitignore
  client/dvm/rpc/src/eth.rs
  client/dvm/rpc/src/lib.rs
  node/rpc/src/pangolin.rs
  node/rpc/src/template.rs
  node/runtime/template/src/pallets/system.rs
  tests/dvm/darwinia/package.json
  tests/dvm/darwinia/tests/0_test-rpc-block.js
  tests/dvm/darwinia/tests/1_test-transfer.js
  tests/dvm/darwinia/tests/2_test-constract-log.js
  tests/dvm/darwinia/tests/3_test-rpc-filter.js
  tests/dvm/darwinia/tests/4_test-solidity-opcodes.js
  tests/dvm/darwinia/tests/bytecode.js
  tests/dvm/darwinia/tests/config.js
  tests/dvm/darwinia/tests/contract/Incrementer.sol
  tests/dvm/darwinia/tests/contract/Opcodes.sol
  tests/dvm/darwinia/tests/contract/RPCTestContract.sol
  tests/dvm/darwinia/tests/contract/compile.js
  tests/dvm/darwinia/tests/contract/test-constract-method.js
  tests/dvm/darwinia/tests/test-bloom.js
  tests/dvm/darwinia/tests/test-gas.js
  tests/dvm/darwinia/tests/test_kton.js
  tests/dvm/darwinia/tests/utils.js
  tests/dvm/frontier/contracts/ECRecoverTests.sol
  tests/dvm/frontier/contracts/ExplicitRevertReason.sol
  tests/dvm/frontier/contracts/Storage.sol
  tests/dvm/frontier/contracts/Test.sol
  tests/dvm/frontier/package.json
  tests/dvm/frontier/tests/test-contract-methods.ts
  tests/dvm/frontier/tests/test-contract-storage.ts
  tests/dvm/frontier/tests/test-contract.ts
  tests/dvm/frontier/tests/test-deprecated.ts
  tests/dvm/frontier/tests/test-filter-api.ts
  tests/dvm/frontier/tests/test-gas.ts
  tests/dvm/frontier/tests/test-log-filtering.ts
  tests/dvm/frontier/tests/test-netapi.ts
  tests/dvm/frontier/tests/test-nonce.ts
  tests/dvm/frontier/tests/test-pending-pool.ts
  tests/dvm/frontier/tests/test-precompiles.ts
  tests/dvm/frontier/tests/test-revert-reason.ts
  tests/dvm/frontier/tests/test-revert-receipt.ts
  tests/dvm/frontier/tests/test-rpc-constants.ts
  tests/dvm/frontier/tests/test-state-root.ts
  tests/dvm/frontier/tests/test-subscription.ts
  tests/dvm/frontier/tests/test-transaction-priority.ts
  tests/dvm/frontier/tests/test-web3api.ts
  tests/dvm/frontier/tests/test_balance.ts
  tests/dvm/frontier/tests/test_block.ts
  tests/dvm/frontier/tests/test_bloom.ts
  tests/dvm/frontier/tests/util.ts
  tests/dvm/frontier/truffle-config.js
  tests/dvm/frontier/tsconfig.json
  tests/dvm/tests/test-rpc-constants.js
  tests/dvm/tests/test-rpc-net.js
  tests/dvm/tests/test-web3api.js
Labels: Test Improvement, CI/CD

#982 Improve CI
  .github/workflows/ci.yml
  .maintain/purge-large-cache.sh
  tests/dvm/frontier/tests/util.ts
Labels: CI/CD

#989 Use `spawn_dvm_tasks` to manage dvm tasks
  client/dvm/rpc/src/overrides/mod.rs
  node/service/src/service/dvm_tasks.rs
  node/service/src/service/mod.rs
  node/service/src/service/pangolin.rs
  node/service/src/service/template.rs
Labels: P9 High

#992 Code Cleaning
  node/rpc/src/pangolin.rs
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/bridge_dispatch.rs
  node/runtime/pangolin/src/pallets/evm_.rs
  node/runtime/pangolin/src/pallets/from_ethereum_issuing_.rs
  node/runtime/pangolin/src/pallets/from_substrate_issuing_.rs
  node/runtime/pangolin/src/pallets/mod.rs
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/bridge_dispatch.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pallets/to_substrate_backing_.rs
  node/runtime/template/src/pallets/evm_.rs
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/pangolin.rs
  node/service/src/chain_spec/pangoro.rs
  node/service/src/service/pangolin.rs
Labels: Housekeeping

#1005 Update evm crates path
  Cargo.toml
  client/dvm/rpc/Cargo.toml
  frame/dvm/Cargo.toml
  frame/evm/Cargo.toml
  frame/evm/precompile/contracts/blake2/Cargo.toml
  frame/evm/precompile/contracts/bn128/Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
  frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
  frame/evm/precompile/contracts/curve25519/Cargo.toml
  frame/evm/precompile/contracts/dispatch/Cargo.toml
  frame/evm/precompile/contracts/ed25519/Cargo.toml
  frame/evm/precompile/contracts/modexp/Cargo.toml
  frame/evm/precompile/contracts/sha3fips/Cargo.toml
  frame/evm/precompile/contracts/simple/Cargo.toml
  frame/evm/precompile/contracts/transfer/Cargo.toml
  frame/evm/precompile/contracts/utils/Cargo.toml
  frame/evm/precompile/contracts/utils/macro/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  primitives/evm/Cargo.toml
  primitives/evm/trace/events/Cargo.toml
  primitives/evm/trace/tracer/Cargo.toml
Labels: Housekeeping
