Repository darwinia-network/darwinia-common, pull requests merged in 2021-01, with the labels that each got.

#438 Code Optimize & Fix Relay Authorities Bug
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
Labels: B2-breaksapi

#440 Update Relay Authorities Protocol
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/test.rs
Labels: D1-runtime-migration

#442 Fix Signed Authorities Ratio
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/test.rs
Labels: D1-runtime-migration

#447 Refactor Relay Authorities
  Cargo.lock
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/src/lib.rs
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/ethereum/backing/src/test_with_relay.rs
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
  primitives/relay/src/relay_authorities.rs
Labels: B2-breaksapi, D1-runtime-migration, E1-new-types

#451 Refactor Apply Scheduled Authorities Change
  bin/node/runtime/pangolin/polkadot-compatible-types.json
  bin/node/runtime/pangolin/types.json
  frame/bridge/ethereum/backing/src/lib.rs
  frame/bridge/ethereum/backing/src/mock.rs
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/test.rs
  primitives/relay/src/relay_authorities.rs
Labels: D1-runtime-migration, E1-new-types

#461 Fix Slash
  frame/bridge/relay-authorities/src/lib.rs
  frame/bridge/relay-authorities/src/mock.rs
  frame/bridge/relay-authorities/src/test.rs
Labels: B2-breaksapi

#463 Dvm update part
  Cargo.lock
  Cargo.toml
  bin/node/runtime/pangolin/Cargo.toml
  bin/node/runtime/pangolin/src/lib.rs
  client/dvm/rpc/Cargo.toml
  client/dvm/rpc/src/eth.rs
  frame/dvm/Cargo.toml
  frame/dvm/rpc/runtime-api/Cargo.toml
  frame/dvm/rpc/src/net.rs
  frame/dvm/src/lib.rs
  frame/dvm/src/mock.rs
  frame/dvm/src/precompiles.rs
  frame/evm/Cargo.toml
  frame/evm/precompile/blake2/Cargo.toml
  frame/evm/precompile/blake2/src/eip_152.rs
  frame/evm/precompile/blake2/src/lib.rs
  frame/evm/precompile/bn128/Cargo.toml
  frame/evm/precompile/bn128/src/lib.rs
  frame/evm/precompile/dispatch/Cargo.toml
  frame/evm/precompile/dispatch/src/lib.rs
  frame/evm/precompile/ed25519/Cargo.toml
  frame/evm/precompile/ed25519/src/lib.rs
  frame/evm/precompile/modexp/Cargo.toml
  frame/evm/precompile/modexp/src/lib.rs
  frame/evm/precompile/simple/Cargo.toml
  frame/evm/precompile/simple/src/lib.rs
  frame/evm/src/lib.rs
  frame/evm/src/runner/builtin.rs
  frame/evm/src/runner/stack.rs
  frame/evm/src/tests.rs
  primitives/dvm-rpc-core/src/block_number.rs
  primitives/dvm-rpc-core/src/call_request.rs
  primitives/dvm-rpc-core/src/index.rs
  primitives/evm/Cargo.toml
  primitives/evm/src/lib.rs
  primitives/evm/src/precompile.rs
  script_tests/package-lock.json
  script_tests/tests/0_test-rpc-block.js
  script_tests/tests/test-rpc-net.js
Labels: dvm
