Repository darwinia-network/darwinia-common, pull requests merged in 2022-08, with the labels that each got.

#1369 Cherrypick #1364
  node/runtime/common/src/impls.rs
Labels: S-Patch

#1373 Use `NextAuthorities` Instead
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/bridge/ecdsa-authority/src/mock.rs
  frame/bridge/ecdsa-authority/src/primitives.rs
  frame/bridge/ecdsa-authority/src/tests.rs
Labels: BK-Storage, BK-API, C-D2E

#1377 Release `v2.8.18`
  Cargo.lock
  frame/balances/Cargo.toml
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/message-gadget/Cargo.toml
  frame/bridge/relay-authority/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/dvm/ethereum/Cargo.toml
  frame/dvm/evm/Cargo.toml
  frame/dvm/evm/precompiles/bls12381/Cargo.toml
  frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml
  frame/dvm/evm/precompiles/dispatch/Cargo.toml
  frame/dvm/evm/precompiles/kton/Cargo.toml
  frame/dvm/evm/precompiles/state-storage/Cargo.toml
  frame/dvm/evm/precompiles/transfer/Cargo.toml
  frame/dvm/evm/precompiles/utils/Cargo.toml
  frame/dvm/evm/precompiles/utils/macro/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/parachain/Cargo.toml
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/cli/Cargo.toml
  node/primitives/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/contract/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/ext/Cargo.toml
  primitives/evm-trace/tracer/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/message/Cargo.toml
  primitives/relayer-game/Cargo.toml
  primitives/s2s/Cargo.toml
Labels: N-Pangolin, U-Release, N-Pangoro

#1383 Emmit Commitment
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/bridge/ecdsa-authority/src/mock.rs
  frame/bridge/ecdsa-authority/src/primitives.rs
  frame/bridge/ecdsa-authority/src/tests.rs
Labels: C-D2E

#1384 Release `v2.8.19`
  Cargo.lock
  frame/balances/Cargo.toml
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/message-gadget/Cargo.toml
  frame/bridge/relay-authority/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/dvm/ethereum/Cargo.toml
  frame/dvm/evm/Cargo.toml
  frame/dvm/evm/precompiles/bls12381/Cargo.toml
  frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml
  frame/dvm/evm/precompiles/dispatch/Cargo.toml
  frame/dvm/evm/precompiles/kton/Cargo.toml
  frame/dvm/evm/precompiles/state-storage/Cargo.toml
  frame/dvm/evm/precompiles/transfer/Cargo.toml
  frame/dvm/evm/precompiles/utils/Cargo.toml
  frame/dvm/evm/precompiles/utils/macro/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/parachain/Cargo.toml
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/cli/Cargo.toml
  node/primitives/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/migrations.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/contract/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/ext/Cargo.toml
  primitives/evm-trace/tracer/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/message/Cargo.toml
  primitives/relayer-game/Cargo.toml
  primitives/s2s/Cargo.toml
Labels: N-Pangolin, U-Release, N-Pangoro

#1387 Custom KTON Metadata
  frame/dvm/evm/precompiles/kton/src/lib.rs
  frame/dvm/evm/precompiles/kton/src/mock.rs
  node/runtime/pangolin/src/pallets/evm.rs
  node/runtime/pangoro/src/pallets/evm.rs
Labels: C-Precompile

#1389 Improve Local Testent Script
  tests/local-testnet/deploy.sh
Labels: U-Test Improvement

#1390 Rename to `MaxEcdsaAuthorities`
  node/runtime/pangolin/src/pallets/ecdsa_authority.rs
  node/runtime/pangoro/src/pallets/ecdsa_authority.rs
Labels: B-Runtime, N-Pangolin, N-Pangoro

#1393 Sync `darwinia-message-bridges` Updates
  Cargo.lock
  frame/dvm/evm/precompiles/state-storage/src/tests.rs
  node/runtime/pangolin/src/pallets/fee_market.rs
  node/runtime/pangoro/src/pallets/fee_market.rs
Labels: C-S2S

#1398 Release `v2.9.0`
  Cargo.lock
  frame/balances/Cargo.toml
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/message-gadget/Cargo.toml
  frame/bridge/relay-authority/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/dvm/ethereum/Cargo.toml
  frame/dvm/evm/Cargo.toml
  frame/dvm/evm/precompiles/bls12381/Cargo.toml
  frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml
  frame/dvm/evm/precompiles/dispatch/Cargo.toml
  frame/dvm/evm/precompiles/kton/Cargo.toml
  frame/dvm/evm/precompiles/state-storage/Cargo.toml
  frame/dvm/evm/precompiles/transfer/Cargo.toml
  frame/dvm/evm/precompiles/utils/Cargo.toml
  frame/dvm/evm/precompiles/utils/macro/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/parachain/Cargo.toml
  frame/wormhole/backing/parachain/src/benchmarking.rs
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/cli/Cargo.toml
  node/primitives/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/contract/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/ext/Cargo.toml
  primitives/evm-trace/tracer/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/message/Cargo.toml
  primitives/relayer-game/Cargo.toml
  primitives/s2s/Cargo.toml
Labels: N-Pangolin, U-Release, N-Pangoro

#1399 Bump Frontier
  Cargo.lock
Labels: C-DVM

#1400 Code Cleaning
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/staking/src/darwinia_tests/inflation.rs
  frame/support/src/lib.rs
  primitives/message/src/network_ids.rs
  primitives/s2s/src/call_params.rs
Labels: U-Housekeeping

#1404 Only keep the lane monitored by the bridgers
  node/runtime/pangolin/src/bridges_message/pangolin_parachain.rs
  node/runtime/pangolin/src/bridges_message/pangoro.rs
  node/runtime/pangoro/src/bridges_message/pangolin.rs
Labels: N-Pangolin, N-Pangoro, C-S2S

#1402 Update Ecdsa Spec
  Cargo.lock
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/bridge/ecdsa-authority/src/primitives.rs
  frame/bridge/ecdsa-authority/src/tests.rs
  frame/bridge/relay-authority/src/lib.rs
  frame/header-mmr/src/lib.rs
  frame/support/src/evm.rs
  node/service/Cargo.toml
Labels: BK-Storage, BK-API, N-Pangolin, N-Pangoro, C-D2E

#1405 Release `v2.9.1`
  Cargo.lock
  frame/balances/Cargo.toml
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/message-gadget/Cargo.toml
  frame/bridge/relay-authority/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/dvm/ethereum/Cargo.toml
  frame/dvm/evm/Cargo.toml
  frame/dvm/evm/precompiles/bls12381/Cargo.toml
  frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml
  frame/dvm/evm/precompiles/dispatch/Cargo.toml
  frame/dvm/evm/precompiles/kton/Cargo.toml
  frame/dvm/evm/precompiles/state-storage/Cargo.toml
  frame/dvm/evm/precompiles/transfer/Cargo.toml
  frame/dvm/evm/precompiles/utils/Cargo.toml
  frame/dvm/evm/precompiles/utils/macro/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/parachain/Cargo.toml
  frame/wormhole/backing/parachain/src/benchmarking.rs
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/cli/Cargo.toml
  node/primitives/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/contract/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/ext/Cargo.toml
  primitives/evm-trace/tracer/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/message/Cargo.toml
  primitives/relayer-game/Cargo.toml
  primitives/s2s/Cargo.toml
Labels: N-Pangolin, U-Release, N-Pangoro

#1407 Delete the staled order
  node/runtime/pangolin/src/migrations.rs
  node/runtime/pangoro/src/migrations.rs
Labels: BK-Storage

#1416 Cargo Clippy
  frame/bridge/ethereum/src/test_data.rs
  frame/bridge/ethereum/src/tests.rs
  frame/bridge/relay-authority/src/mock.rs
  frame/bridge/relay-authority/src/test.rs
  frame/bridge/relayer-game/src/mock.rs
  frame/bridge/relayer-game/src/tests.rs
  frame/dvm/evm/precompiles/kton/src/mock.rs
  frame/dvm/evm/precompiles/kton/src/tests.rs
  frame/dvm/evm/precompiles/state-storage/src/tests.rs
  frame/dvm/evm/precompiles/utils/src/data/tests.rs
  frame/wormhole/backing/ethereum/src/tests.rs
  primitives/ethereum/src/receipt.rs
  primitives/ethereum/src/tests.rs
  primitives/merkle-patricia-trie/src/nibbles.rs
  primitives/merkle-patricia-trie/src/tests.rs
  primitives/merkle-patricia-trie/src/trie.rs
Labels: U-Housekeeping

#1415 Refresh Message Root After Authority Changed
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/bridge/ecdsa-authority/src/tests.rs
Labels: C-D2E

#1417 Ceil the Multiply Result
  frame/bridge/ecdsa-authority/src/lib.rs
  frame/bridge/ecdsa-authority/src/tests.rs
Labels: B-Runtime, U-Test Improvement, C-D2E

#1418 Release `v2.9.3`
  Cargo.lock
  frame/balances/Cargo.toml
  frame/bridge/ecdsa-authority/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/message-gadget/Cargo.toml
  frame/bridge/relay-authority/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/dvm/ethereum/Cargo.toml
  frame/dvm/evm/Cargo.toml
  frame/dvm/evm/precompiles/bls12381/Cargo.toml
  frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml
  frame/dvm/evm/precompiles/dispatch/Cargo.toml
  frame/dvm/evm/precompiles/kton/Cargo.toml
  frame/dvm/evm/precompiles/state-storage/Cargo.toml
  frame/dvm/evm/precompiles/transfer/Cargo.toml
  frame/dvm/evm/precompiles/utils/Cargo.toml
  frame/dvm/evm/precompiles/utils/macro/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/staking/Cargo.toml
  frame/support/Cargo.toml
  frame/transaction-pause/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/parachain/Cargo.toml
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/cli/Cargo.toml
  node/primitives/Cargo.toml
  node/rpc/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/migrations.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/migrations.rs
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/contract/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/ext/Cargo.toml
  primitives/evm-trace/tracer/Cargo.toml
  primitives/merkle-patricia-trie/Cargo.toml
  primitives/message/Cargo.toml
  primitives/relayer-game/Cargo.toml
  primitives/s2s/Cargo.toml
Labels: N-Pangolin, U-Release, N-Pangoro

#1419 Bump Substrate Deps
  Cargo.lock
Labels: C-Substrate
