Repository darwinia-network/darwinia-common, pull requests merged in 2022-01, with the labels that each got.

#1030 Try LTO
  .github/workflows/ci.yml
  Cargo.toml
Labels: CI/CD

#1034 Add Migrations
  Cargo.lock
  node/runtime/pangolin/src/lib.rs
Labels: Pangolin

#1038 Add Migration
  Cargo.lock
  README.md
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/mod.rs
  node/runtime/pangolin/src/pallets/randomness_collective_flip.rs
  node/runtime/pangolin/src/pallets/society.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/runtime/pangoro/src/pallets/randomness_collective_flip.rs
  node/runtime/template/Cargo.toml
  node/runtime/template/src/lib.rs
  node/runtime/template/src/pallets/mod.rs
  node/runtime/template/src/pallets/randomness_collective_flip.rs
  shell.nix
Labels: Pangolin, Pangoro

#1031 DVM signed transaction
  Cargo.lock
  client/dvm/db/Cargo.toml
  client/dvm/rpc/Cargo.toml
  frame/dvm/Cargo.toml
  frame/dvm/rpc/Cargo.toml
  frame/dvm/rpc/runtime-api/Cargo.toml
  frame/dvm/src/lib.rs
  frame/dvm/src/mock.rs
  frame/dvm/src/tests.rs
  frame/evm/Cargo.toml
  frame/evm/precompile/contracts/bridge/bsc/Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
  frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
  frame/evm/precompile/contracts/dispatch/Cargo.toml
  frame/evm/precompile/contracts/transfer/Cargo.toml
  frame/support/src/evm.rs
  frame/wormhole/issuing/ethereum/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  frame/wormhole/issuing/s2s/src/mock.rs
  node/rpc/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/template/Cargo.toml
  node/runtime/template/src/lib.rs
  node/service/Cargo.toml
Labels: P9 High

#1046 CI MetadataV14
  .github/workflows/ci.yml
Labels: CI/CD

#1033 DVM Update
  Cargo.lock
  client/dvm/rpc/src/eth.rs
  frame/dvm/Cargo.toml
  frame/dvm/src/lib.rs
  frame/dvm/src/mock.rs
  frame/evm/precompile/contracts/bridge/bsc/src/lib.rs
  frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/src/lib.rs
  frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
  frame/evm/precompile/contracts/bridge/s2s/src/lib.rs
  frame/evm/precompile/contracts/dispatch/Cargo.toml
  frame/evm/precompile/contracts/dispatch/src/lib.rs
  frame/evm/precompile/contracts/transfer/Cargo.toml
  frame/evm/precompile/contracts/transfer/src/kton.rs
  frame/evm/precompile/contracts/transfer/src/lib.rs
  frame/evm/precompile/contracts/transfer/src/ring.rs
  frame/support/src/evm.rs
  node/runtime/pangolin/src/pallets/evm_.rs
  tests/dvm/darwinia/tests/test-gas.js
  tests/dvm/frontier/tests/test-gas.ts
Labels: P8 High

#1050 Add DVM To Pangoro
  Cargo.lock
  node/cli/src/command.rs
  node/rpc/Cargo.toml
  node/rpc/src/pangoro.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/dvm.rs
  node/runtime/pangoro/src/pallets/evm.rs
  node/runtime/pangoro/src/pallets/mod.rs
  node/service/src/chain_spec/pangoro.rs
  node/service/src/service/pangoro.rs
Labels: P8 High
