Repository darwinia-network/darwinia-common, pull requests merged in 2022-03, with the labels that each got.

#1113 Code Cleaning
  Cargo.lock
  client/dvm/rpc/Cargo.toml
  client/dvm/tracer/Cargo.toml
  frame/balances/Cargo.toml
  frame/balances/rpc/Cargo.toml
  frame/balances/rpc/runtime-api/Cargo.toml
  frame/beefy-gadget/Cargo.toml
  frame/bridge/bsc/Cargo.toml
  frame/bridge/ethereum/Cargo.toml
  frame/bridge/relay-authorities/Cargo.toml
  frame/bridge/relayer-game/Cargo.toml
  frame/claims/Cargo.toml
  frame/democracy/Cargo.toml
  frame/dvm/Cargo.toml
  frame/dvm/rpc/Cargo.toml
  frame/elections-phragmen/Cargo.toml
  frame/evm/Cargo.toml
  frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
  frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
  frame/evm/precompile/contracts/dispatch/Cargo.toml
  frame/evm/precompile/contracts/transfer/Cargo.toml
  frame/fee-market/Cargo.toml
  frame/fee-market/rpc/Cargo.toml
  frame/fee-market/rpc/runtime-api/Cargo.toml
  frame/header-mmr/Cargo.toml
  frame/header-mmr/rpc/Cargo.toml
  frame/header-mmr/rpc/runtime-api/Cargo.toml
  frame/staking/Cargo.toml
  frame/staking/rpc/Cargo.toml
  frame/staking/rpc/runtime-api/Cargo.toml
  frame/support/Cargo.toml
  frame/support/src/evm.rs
  frame/support/src/lib.rs
  frame/support/src/tests.rs
  frame/transaction-pause/Cargo.toml
  frame/vesting/Cargo.toml
  frame/wormhole/backing/ethereum/Cargo.toml
  frame/wormhole/backing/s2s/Cargo.toml
  frame/wormhole/backing/tron/Cargo.toml
  frame/wormhole/issuing/ethereum/Cargo.toml
  frame/wormhole/issuing/s2s/Cargo.toml
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangoro/Cargo.toml
  node/runtime/template/Cargo.toml
  node/service/Cargo.toml
  primitives/asset/Cargo.toml
  primitives/asset/src/lib.rs
  primitives/bsc/Cargo.toml
  primitives/ethereum/Cargo.toml
  primitives/evm-trace/events/Cargo.toml
  primitives/fee-market/Cargo.toml
  primitives/fee-market/src/lib.rs
  primitives/relay/Cargo.toml
  primitives/relay/src/lib.rs
  primitives/s2s/Cargo.toml
  primitives/s2s/src/call_params.rs
  primitives/s2s/src/lib.rs
Labels: Housekeeping

#1125 Clean Service Part.1
  frame/staking/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/rpc/src/lib.rs
  node/rpc/src/template.rs
  node/runtime/pangolin/src/pallets/proxy.rs
  node/service/src/service/api.rs
  node/service/src/service/dvm.rs
  node/service/src/service/dvm_tasks.rs
  node/service/src/service/mod.rs
  node/service/src/service/pangolin.rs
  node/service/src/service/pangoro.rs
  node/service/src/service/template.rs
Labels: Need Darwinia Companion PR

#1129 Code Cleaning
  Cargo.lock
  node/cli/build.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/primitives/bridge/Cargo.toml
  node/primitives/bridge/src/lib.rs
  node/rpc/src/lib.rs
  node/rpc/src/template.rs
  node/runtime/common/Cargo.toml
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/election_provider_multi_phase.rs
  node/runtime/pangolin/src/pallets/staking.rs
  node/runtime/pangoro/Cargo.toml
  node/runtime/pangoro/src/lib.rs
  node/runtime/pangoro/src/pallets/election_provider_multi_phase.rs
  node/runtime/pangoro/src/pallets/staking.rs
  node/runtime/template/Cargo.toml
  node/runtime/template/src/lib.rs
  node/service/Cargo.toml
  node/service/src/client.rs
  node/service/src/service/dvm.rs
  node/service/src/service/mod.rs
  node/service/src/service/template.rs
Labels: Housekeeping

#1117 Add `pallet-bridge-grandpa`, `pallet-bridge-parachains` to Pangolin
  Cargo.lock
  node/runtime/pangolin/Cargo.toml
  node/runtime/pangolin/src/lib.rs
  node/runtime/pangolin/src/pallets/bridge_grandpa.rs
  node/runtime/pangolin/src/pallets/bridge_parachains.rs
  node/runtime/pangolin/src/pallets/mod.rs
Labels: Pangolin, S2S

#1122 Fix priority fee to block author
  frame/dvm/ethereum/src/mock.rs
  frame/dvm/evm/src/lib.rs
  frame/dvm/evm/src/tests.rs
  frame/wormhole/issuing/s2s/src/mock.rs
  node/cli/Cargo.toml
  node/runtime/pangolin/src/pallets/evm.rs
  node/runtime/pangoro/src/pallets/evm.rs
  node/runtime/template/src/pallets/evm.rs
Labels: Need Darwinia Companion PR

#1149 Rewrite darwinia tests with TS
  .prettierignore 
  tests/dvm/darwinia/package.json
  tests/dvm/darwinia/tests/0-test-block.ts
  tests/dvm/darwinia/tests/1-test-transfer.ts
  tests/dvm/darwinia/tests/2-test-log.ts
  tests/dvm/darwinia/tests/3-test-filter.ts
  tests/dvm/darwinia/tests/3_test-rpc-filter.js
  tests/dvm/darwinia/tests/4-test-opcodes.ts
  tests/dvm/darwinia/tests/4_test-solidity-opcodes.js
  tests/dvm/darwinia/tests/bytecode.js
  tests/dvm/darwinia/tests/config.ts
  tests/dvm/darwinia/tests/contract/TestLog.sol
  tests/dvm/darwinia/tests/contract/compile.ts
  tests/dvm/darwinia/tests/contract/contract_info.ts
  tests/dvm/darwinia/tests/test-bloom.ts
  tests/dvm/darwinia/tests/test-constract.ts
  tests/dvm/darwinia/tests/test-gas.js
  tests/dvm/darwinia/tests/utils.js
  tests/dvm/darwinia/tests/utils.ts
  tests/dvm/darwinia/tsconfig.json
  tests/dvm/frontier/package.json
  tests/dvm/frontier/tests/test-contract-methods.ts
  tests/dvm/frontier/tests/test-contract-storage.ts
  tests/dvm/frontier/tests/test-contract.ts
  tests/dvm/frontier/tests/test-fee-history.ts
  tests/dvm/frontier/tests/test-filter-api.ts
  tests/dvm/frontier/tests/test-gas.ts
  tests/dvm/frontier/tests/test-log-filtering.ts
  tests/dvm/frontier/tests/test-nonce.ts
  tests/dvm/frontier/tests/test-pending-pool.ts
  tests/dvm/frontier/tests/test-precompiles.ts
  tests/dvm/frontier/tests/test-revert-reason.ts
  tests/dvm/frontier/tests/test-revert-receipt.ts
  tests/dvm/frontier/tests/test-rpc-constants.ts
  tests/dvm/frontier/tests/test-subscription.ts
  tests/dvm/frontier/tests/test-transaction-priority.ts
  tests/dvm/frontier/tests/test-transaction-version.ts
  tests/dvm/frontier/tests/test_balance.ts
  tests/dvm/frontier/tests/test_block.ts
  tests/dvm/frontier/tests/test_bloom.ts
  tests/dvm/frontier/tests/util.ts
  tests/dvm/frontier/truffle-config.js
Labels: Test Improvement
